

const String websitePartA = "<!DOCTYPE html>\n"
                            "<html>\n"
                            "<head>\n"
                            "<meta charset='UTF-8'/>\n"
                            "<meta http-equiv='content-type' content='text/html'/>\n"
                            "<meta name='viewport' content='width=device-width, initial-scale=1.0'/>\n"
                            "<style>\n"
                            "body { background-color: #222;color: #CCC;font-family: 'Kristen ITC', Comic Sans, sans-serif }\n"
                            "button { border-radius: 12px;background-color: #cf3;border: none;color: black;padding: 10px;text-align: center;text-decoration: none;display: inline-block;font-size: 12px;margin: 4px 2px;cursor: pointer; }\n"
                            "button.predefined_color_button { border-radius: 50%; height: 40px; width:40px; margin: 5px; }\n"
                            "range { background-color: #00000000; }\n"
                            "</style>\n"
                            "<title>Nestbeleuchtung</title>\n"
                            "<script type='text/javascript'>\n"
                            "var red = 0;var green = 0;var blue = 0;\n"
                            "function UpdateColorDisplay(r, g, b, overrideColor) {\n"
                            "  var hexString = ((r << 16) + (g << 8) + b).toString(16);\n"
                            "  var extendedHexString = '000000' + hexString.toUpperCase();\n"
                            "  var colorCode = '#' + (extendedHexString).slice(-6);\n"
                            "  var div = document.getElementById('divpreview');\n"
                            "  if(overrideColor === undefined) { div.style.backgroundColor = colorCode; }\n"
                            "  else { div.style.backgroundColor = overrideColor; }\n"
                            "  div.innerHTML = colorCode;\n"
                            "  if((r + g + b) < 128) { div.style.color = '#FFC'; }\n"
                            "  else { div.style.color = '#000'; }\n"
                            "  document.getElementById('Slider_Rot').value = r;\n"
                            "  document.getElementById('Slider_Gras').value = g;\n"
                            "  document.getElementById('Slider_Blau').value = b;\n"
                            "}\n"
                            "function ReadColor() {\n"
                            "  var xmlHttp = new XMLHttpRequest();\n"
                            "  xmlHttp.onreadystatechange = function() {\n"
                            "    if (xmlHttp.readyState == 4 && xmlHttp.status == 200) {\n"
                            "        var entries = xmlHttp.responseText.split('\\n');\n"
                            "        red = Number(entries[0]);\n"
                            "        green = Number(entries[1]);\n"
                            "        blue = Number(entries[2]);\n"
                            "        UpdateColorDisplay(red, green, blue);\n"
                            "    }\n"
                            "  }\n"
                            "  xmlHttp.open('GET', 'http://";
const String websitePartB = "/Data.plain', true);\n"
                            "  xmlHttp.send(null);\n"
                            "}\n"
                            "function clickColor(r, g, b, time, overrideColor) {\n"
                            "  red = r;\n"
                            "  green = g;\n"
                            "  blue = b;\n"
                            "  var request = new XMLHttpRequest();\n"
                            "  request.open('POST', 'http://";
const String websitePartC = "', true);\n"
                            "  request.send('r' + red + 'g' + green + 'b' + blue + 't' + time);\n"
                            "  UpdateColorDisplay(red, green, blue, overrideColor);\n"
                            "}\n"
                            "ReadColor();\n"
                            "</script>\n"
                            "</head>\n"
                            "<body>\n"
                            "<div>\n"
                            "<h1><u>Bett Beleuchtung</u></h1>\n"
                            "<p><u><font color='#f00'>F</font><font color='#f60'>a</font><font color='#fd0'>r</font><font color='#bf0'>b</font><font color='#4f0'>e</font><font color='#0f2'>i</font><font color='#0f9'>n</font><font color='#0ff'>s</font><font color='#09f'>t</font><font color='#02f'>e</font><font color='#40f'>l</font><font color='#b0f'>l</font><font color='#f0d'>u</font><font color='#f06'>n</font><font color='#f00'>g</font></u>:</p>\n"
                            "<div>\n"
                            "<button class='predefined_color_button' style='background-color: #FFFFEF' onclick='clickColor(0xFF, 0xff, 0x98, 0, getComputedStyle(this)[\"background-color\"])'/>\n"
                            "<button class='predefined_color_button' style='background-color: #D88700' onclick='clickColor(0xA2, 0x2A, 0x00, 0, getComputedStyle(this)[\"background-color\"])'/>\n"
                            "<button class='predefined_color_button' style='background-color: #FF6800' onclick='clickColor(0xFF, 0x28, 0x00, 0, getComputedStyle(this)[\"background-color\"])'/>\n"
                            "</div>\n"
                            "<div>\n"
                            "<button class='predefined_color_button' style='background-color: #F6FD00' onclick='clickColor(0xA4, 0x51, 0x00, 0, getComputedStyle(this)[\"background-color\"])'/>\n"
                            "<button class='predefined_color_button' style='background-color: #600000' onclick='clickColor(0x09, 0x00, 0x00, 0, getComputedStyle(this)[\"background-color\"])'/>\n"
                            "<button class='predefined_color_button' style='background-color: #A1008A' onclick='clickColor(0xA1, 0x00, 0x8A, 0, getComputedStyle(this)[\"background-color\"])'/>\n"
                            "</div>\n"
                            "<div>\n"
                            "<button class='predefined_color_button' style='background-color: #009900' onclick='clickColor(0x00, 0x6c, 0x00, 0, getComputedStyle(this)[\"background-color\"])'/>\n"
                            "<button class='predefined_color_button' style='background-color: #00B39C' onclick='clickColor(0x00, 0x6C, 0x36, 0, getComputedStyle(this)[\"background-color\"])'/>\n"
                            "<button class='predefined_color_button' style='background-color: #A1004C' onclick='clickColor(0xA1, 0x00, 0x1F, 0, getComputedStyle(this)[\"background-color\"])'/>\n"
                            "</div>\n"
                            "<div style='width:236px;'>\n"
                            "<div id='divpreview' style='background-color: rgb(0,0,0); text-align: center;color: #000;font-family: mono;'>&nbsp;</div>\n"
                            "</div>\n"
                            "<div style='margin:10px'>\n"
                            "<u>Timer</u>:<br/>\n"
                            "<button onclick='clickColor(0,0,0,0)'>sofort</button>\n"
                            "<button onclick='clickColor(0,0,0,15*60*1000)'>in 15 min.</button>\n"
                            "<button onclick='clickColor(0,0,0,30*60*1000)'>in 30 min.</button>\n"
                            "</div>\n"
                            "<div style='margin:10px'>\n"
                            "<u>Regler</u>:<br/>\n"
                            "<table>\n"
                            "<tr><td>Rot:</td><td><input type='range' min='0' max='255' value='0' class='slider' id='Slider_Rot'></td></tr>\n"
                            "<tr><td>Gr&uuml;n:</td><td><input type='range' min='0' max='255' value='0' class='slider' id='Slider_Gras'> </td></tr>\n"
                            "<tr><td>Blau:</td><td><input type='range' min='0' max='255' value='0' class='slider' id='Slider_Blau'> </td></tr>\n"
                            "</table>\n"
                            "</div>\n"
                            "<script type='text/javascript'>\n"
                            "var Rot = document.getElementById('Slider_Rot');\n"
                            "Rot.oninput = function() { clickColor (parseInt(this.value), green, blue, 0); }\n"
                            "var Gras = document.getElementById('Slider_Gras');\n"
                            "Gras.oninput = function() { clickColor (red, parseInt(this.value), blue, 0); }\n"
                            "var Blau = document.getElementById('Slider_Blau');\n"
                            "Blau.oninput = function() { clickColor (red, green, parseInt(this.value), 0); }\n"
                            "</script>\n"
                            "</div>\n"
                            "</body>\n"
                            "</html>\n";

const String configsitePartA = "<!DOCTYPE html>\n"
                               "<html>\n"
                               "<head>\n"
                               "<meta charset='UTF-8'/>\n"
                               "<meta http-equiv='content-type' content='text/html'/>\n"
                               "<meta name='viewport' content='width=device-width, initial-scale=1.0'/>\n"
                               "<style>\n"
                               "body { background-color: #222;color: #CCC;font-family: 'Kristen ITC', Comic Sans, sans-serif; }\n"
                               "input, select { background-color: #111;color: #CCC;font-family: 'Kristen ITC', Comic Sans, sans-serif; margin: 4px 2px; border: none; min-width: 250px;}\n"
                               "button { border-radius: 12px;background-color: #cf3;border: none;color: black;padding: 10px;text-align: center;text-decoration: none;display: inline-block;font-size: 12px;margin: 4px 2px;cursor: pointer; }\n"
                               "</style>\n"
                               "<title>Nestbeleuchtung</title>\n"
                               "<script type='text/javascript'>\n"
                               "function SendData() {\n"
                               "  var postData = '';\n"
                               "  var auth_key = document.getElementById('auth_key').value;\n"
                               "  var new_auth_key = document.getElementById('new_auth_key').value;\n"
                               "  postData += ';auth_key:' + auth_key;\n"
                               "  if(new_auth_key == '') {\n"
                               "    postData += ';new_auth_key:' + auth_key;\n"
                               "  } else {\n"
                               "    postData += ';new_auth_key:' + new_auth_key;\n"
                               "  }\n"
                               "  postData += ';mode:' + document.getElementById('mode').value;\n"
                               "  postData += ';wlan_ssid:' + document.getElementById('wlan_ssid').value;\n"
                               "  postData += ';wlan_pwd:' + document.getElementById('wlan_password').value;\n"
                               "  postData += ';hostname:' + document.getElementById('hostname').value;\n"
                               "  var xmlHttp = new XMLHttpRequest();\n"
                               "  xmlHttp.onreadystatechange = function() {\n"
                               "    if (xmlHttp.readyState == 4) {\n"
                               "      if(xmlHttp.status == 200) {\n"
                               "        document.getElementById('result_div').innerHTML = 'Values Set.';\n"
                               "      } else {\n"
                               "        document.getElementById('result_div').innerHTML = 'Failed to set Values.<br/>Reported error code is: ' + xmlHttp.status;\n"
                               "      }\n"
                               "    }\n"
                               "  }\n"
                               "  xmlHttp.open('POST', 'http://";
const String configsitePartB = "/config.plain', true);\n"
                               "  xmlHttp.send(postData);\n"
                               "}\n"
                               "</script>\n"
                               "</head>\n"
                               "<body>\n"
                               "<h2>Configuration</h2>\n"
                               "<dl>\n"
                               "<dt><label for='auth_key'>Auth-Key</label></dt>\n"
                               "<dd><input type='text' id='auth_key' pattern='[^;:]{8,100}' value=''/></dd>\n"
                               "<dt><label for='new_auth_key'>New Auth-Key</label></dt>\n"
                               "<dd><input type='text' id='new_auth_key' pattern='[^;:]{8,100}' value=''/></dd>\n"
                               "<dt><label for='mode'>Mode</label></dt>\n"
                               "<dd>\n"
                               "<select id='mode'>\n"
                               "<option value='0' ";
const String configsitePartC = ">Accesspoint</option>\n"
                               "<option value='1' ";
const String configsitePartD = ">Join WiFi</option>\n"
                               "</select>\n"
                               "</dd>\n"
                               "<dt><label for='wlan_ssid'>WLAN-SSID</label></dt>\n"
                               "<dd><input type='text' id='wlan_ssid' pattern='[^;:]{1,32}' value='";
const String configsitePartE = "'/></dd>\n"
                               "<dt><label for='wlan_password'>WLAN-Password</label></dt>\n"
                               "<dd><input type='text' id='wlan_password' pattern='[^;:]{8,63}' value=''/></dd>\n"
                               "<dt><label for='hostname'>Hostname</label></dt>\n"
                               "<dd><input type='text' id='hostname' pattern='[^;:]{1,253}' value='";
const String configsitePartF = "'/></dd>\n"
                               "</dl>\n"
                               "<button onclick='SendData()' style='min-width: 150px'>Submit</button>\n"
                               "<div id='result_div'>\n"
                               "&nbsp;\n"
                               "</div>\n"
                               "</body>\n"
                               "</html>\n";
